version: "3"
services:
  recordstore:
    image: tomcat
    build: '.'
    stdin_open: true
    ports:
      - 8080:8080
      - 5005:5005
  recordstoredb:
    image: mariadb
    build: './mariadb/'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root